remote_theme: MicrosoftLearning/Jekyll-Theme
title: Simple Basic Labs
description: Beginner-friendly browser labs published with GitHub Pages
url: https://xianbinzhang1.github.io
baseurl: /Simple-Basic-Labs
exclude:
  - readme.md
  - .github/
header_pages:
  - index.html
author: Microsoft Learning
twitter_username: mslearning
github_username:  MicrosoftLearning
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true